"""empty message

Revision ID: 04061023d93b
Revises: 432dc7f58e91
Create Date: 2020-05-29 07:43:14.079520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04061023d93b'
down_revision = '432dc7f58e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('store_circle_name', sa.String(length=100), nullable=True, comment='商圈名称'),
    sa.Column('is_sensitive', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否为敏感商圈，True敏感 False不敏感'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circle_is_delete'), 'circle', ['is_delete'], unique=False)
    op.drop_index('ix_codetable_is_delete', table_name='codetable')
    op.drop_table('codetable')
    op.alter_column('case', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment=' 零售户id')
    op.add_column('casecigar', sa.Column('business_number', sa.String(length=200), nullable=True, comment='违法零售户许可证号'))
    op.add_column('casecigar', sa.Column('case_date', sa.DateTime(), nullable=True, comment='案发时间'))
    op.add_column('casecigar', sa.Column('case_nature', sa.String(length=128), nullable=True, comment='案件性质'))
    op.add_column('casecigar', sa.Column('cigar_codebehind', sa.String(length=128), nullable=True, comment='后16位喷码'))
    op.add_column('casecigar', sa.Column('cigar_codefront', sa.String(length=128), nullable=True, comment='前16位喷码'))
    op.add_column('casecigar', sa.Column('singlebrandname', sa.String(length=128), nullable=True, comment='品规名'))
    op.add_column('casecigar', sa.Column('store_name', sa.String(length=128), nullable=True, comment='违法零售户名'))
    op.alter_column('casecigar', 'case_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment=' 违法案件id')
    op.alter_column('casecigar', 'count',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='卷烟数量',
               existing_comment='卷烟数量（条数）',
               existing_nullable=True)
    op.alter_column('casecigar', 'origin_area',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True,
               existing_comment='来源地')
    op.drop_constraint('casecigar_ibfk_2', 'casecigar', type_='foreignkey')
    op.drop_column('casecigar', 'singlebrand_id')
    op.alter_column('purchase', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment=' 零售户id')
    op.add_column('store', sa.Column('special_History', sa.Enum('VIOLENCE', 'PSYCHOSIS', 'IMPORTUNE', 'COMPLAINT', 'COMPLEX', name='specialhistoryenum'), nullable=True, comment='特殊历史类别'))
    op.alter_column('store', 'circle',
               existing_type=mysql.TINYINT(display_width=1),
               comment='商圈',
               existing_comment='是否敏感商圈，True敏感(商工住) False不敏感(文办混)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index('ix_store_circle', table_name='store')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_store_circle', 'store', ['circle'], unique=False)
    op.alter_column('store', 'circle',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否敏感商圈，True敏感(商工住) False不敏感(文办混)',
               existing_comment='商圈',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_column('store', 'special_History')
    op.alter_column('purchase', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment=' 零售户id')
    op.add_column('casecigar', sa.Column('singlebrand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='品规id'))
    op.create_foreign_key('casecigar_ibfk_2', 'casecigar', 'singlebrand', ['singlebrand_id'], ['id'])
    op.alter_column('casecigar', 'origin_area',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False,
               existing_comment='来源地')
    op.alter_column('casecigar', 'count',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='卷烟数量（条数）',
               existing_comment='卷烟数量',
               existing_nullable=True)
    op.alter_column('casecigar', 'case_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment=' 违法案件id')
    op.drop_column('casecigar', 'store_name')
    op.drop_column('casecigar', 'singlebrandname')
    op.drop_column('casecigar', 'cigar_codefront')
    op.drop_column('casecigar', 'cigar_codebehind')
    op.drop_column('casecigar', 'case_nature')
    op.drop_column('casecigar', 'case_date')
    op.drop_column('casecigar', 'business_number')
    op.alter_column('case', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment=' 零售户id')
    op.create_table('codetable',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('singlebrand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='品规id'),
    sa.Column('case_cigarid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='违法涉烟详情id'),
    sa.Column('cigar_codefront', mysql.VARCHAR(length=128), nullable=False, comment='前16位喷码'),
    sa.Column('cigar_codebehind', mysql.VARCHAR(length=128), nullable=False, comment='后16位喷码'),
    sa.ForeignKeyConstraint(['case_cigarid'], ['casecigar.id'], name='codetable_ibfk_1'),
    sa.ForeignKeyConstraint(['singlebrand_id'], ['singlebrand.id'], name='codetable_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_codetable_is_delete', 'codetable', ['is_delete'], unique=False)
    op.drop_index(op.f('ix_circle_is_delete'), table_name='circle')
    op.drop_table('circle')
    # ### end Alembic commands ###
