"""empty message

Revision ID: 2b70073c9ba2
Revises: 69ec184b472b
Create Date: 2020-05-30 23:00:18.291863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b70073c9ba2'
down_revision = '69ec184b472b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circle', 'store_circle_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='零售户商圈名称',
               existing_comment='商圈名称',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('circle', 'store_circle_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='商圈名称',
               existing_comment='零售户商圈名称',
               existing_nullable=True)
    # ### end Alembic commands ###
