"""empty message

Revision ID: 432dc7f58e91
Revises: 
Create Date: 2020-05-27 19:11:57.374543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432dc7f58e91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('author_name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorities_is_delete'), 'authorities', ['is_delete'], unique=False)
    op.create_table('businessformat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('business_format', sa.String(length=50), nullable=True, comment='经营业态'),
    sa.Column('degree', sa.Integer(), nullable=True, comment='业态等级'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businessformat_is_delete'), 'businessformat', ['is_delete'], unique=False)
    op.create_table('canton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('canton', sa.String(length=128), nullable=True, comment='行政区'),
    sa.Column('is_cantonsensitivity', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='行政区是否敏感，True敏感 False不敏感'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canton_is_cantonsensitivity'), 'canton', ['is_cantonsensitivity'], unique=False)
    op.create_index(op.f('ix_canton_is_delete'), 'canton', ['is_delete'], unique=False)
    op.create_table('excelinandout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('input_caseid', sa.String(length=128), nullable=True, comment='案件编号'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='稽查员用户id'),
    sa.Column('singlebrand_id', sa.String(length=128), nullable=True, comment='规格id'),
    sa.Column('singlebrand_name', sa.String(length=128), nullable=True, comment='品规名'),
    sa.Column('code_front', sa.String(length=16), nullable=True, comment='喷码前16位'),
    sa.Column('code_behind', sa.String(length=16), nullable=True, comment='喷码后16位'),
    sa.Column('count', sa.DECIMAL(precision=8, scale=1), nullable=True, comment='条数'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excelinandout_is_delete'), 'excelinandout', ['is_delete'], unique=False)
    op.create_table('monthtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('month', sa.Integer(), nullable=True, comment='月份'),
    sa.Column('degree', sa.Integer(), nullable=True, comment='敏感月等级'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthtable_is_delete'), 'monthtable', ['is_delete'], unique=False)
    op.create_table('personinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='法人姓名'),
    sa.Column('sex', sa.String(length=20), nullable=False, comment='性别'),
    sa.Column('id_card', sa.String(length=128), nullable=False, comment='法人身份证号'),
    sa.Column('id_address', sa.String(length=128), nullable=True, comment='身份证住址'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('nation', sa.String(length=128), nullable=True, comment='民族'),
    sa.Column('census_register', sa.String(length=128), nullable=True, comment='户籍'),
    sa.Column('phone', sa.String(length=128), nullable=True, comment='联系电话'),
    sa.Column('address', sa.String(length=128), nullable=True, comment='当前住址'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personinfo_is_delete'), 'personinfo', ['is_delete'], unique=False)
    op.create_table('predictrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('rule_name', sa.String(length=128), nullable=True, comment='规则名称'),
    sa.Column('parameter1', sa.Integer(), nullable=True, comment='参数一'),
    sa.Column('parameter2', sa.Integer(), nullable=True, comment='参数二'),
    sa.Column('parameter3', sa.Integer(), nullable=True, comment='参数三'),
    sa.Column('parameter4', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='参数'),
    sa.Column('score1', sa.Integer(), nullable=True, comment='分数一'),
    sa.Column('score2', sa.Integer(), nullable=True, comment='分数二'),
    sa.Column('score3', sa.Integer(), nullable=True, comment='分数三'),
    sa.Column('score4', sa.Integer(), nullable=True, comment='分数四'),
    sa.Column('describe_rule', sa.String(length=128), nullable=True, comment='预警参数描述'),
    sa.Column('modifydate', sa.Date(), nullable=True, comment='修改日期'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictrule_is_delete'), 'predictrule', ['is_delete'], unique=False)
    op.create_index(op.f('ix_predictrule_parameter4'), 'predictrule', ['parameter4'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('role_name', sa.Enum('ADMIN', 'STATION_ADMIN', 'DEPART_ADMIN', 'USER', 'CAPTAIN_ADMIN', name='roleenum'), nullable=True, comment='角色名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_is_delete'), 'role', ['is_delete'], unique=False)
    op.create_table('singlebrand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('singlebrand_name', sa.String(length=128), nullable=True, comment='品规名称'),
    sa.Column('wholesale_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='批发价'),
    sa.Column('retail_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='零售价'),
    sa.Column('is_sale', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否在销'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_singlebrand_is_delete'), 'singlebrand', ['is_delete'], unique=False)
    op.create_index(op.f('ix_singlebrand_is_sale'), 'singlebrand', ['is_sale'], unique=False)
    op.create_table('socialrelationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('relationship_name', sa.String(length=128), nullable=True, comment='关系名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socialrelationship_is_delete'), 'socialrelationship', ['is_delete'], unique=False)
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('station_name', sa.String(length=50), nullable=True, comment='专卖局名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_is_delete'), 'station', ['is_delete'], unique=False)
    op.create_table('warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('mode', sa.Enum('SVM', 'BP', 'RULE', name='modelenum'), nullable=True, comment='预测模型'),
    sa.Column('warning_param1', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='预警等级参数1'),
    sa.Column('warning_param2', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='预警等级参数2'),
    sa.Column('warning_param3', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='预警等级参数3'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warning_is_delete'), 'warning', ['is_delete'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('depart_name', sa.String(length=50), nullable=True, comment='稽查所名称'),
    sa.Column('station_id', sa.Integer(), nullable=False, comment='专卖局id'),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_is_delete'), 'department', ['is_delete'], unique=False)
    op.create_table('limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('subbrand_id', sa.Integer(), nullable=True, comment='品规id'),
    sa.Column('A2', sa.Integer(), nullable=True, comment='A2零售户限量'),
    sa.Column('A3', sa.Integer(), nullable=True, comment='A3零售户限量'),
    sa.Column('A4', sa.Integer(), nullable=True, comment='A4零售户限量'),
    sa.Column('A5', sa.Integer(), nullable=True, comment='A5零售户限量'),
    sa.Column('B1', sa.Integer(), nullable=True, comment='B1零售户限量'),
    sa.Column('B2', sa.Integer(), nullable=True, comment='B2零售户限量'),
    sa.Column('B3', sa.Integer(), nullable=True, comment='B3零售户限量'),
    sa.Column('B4', sa.Integer(), nullable=True, comment='B4零售户限量'),
    sa.Column('C1', sa.Integer(), nullable=True, comment='C1零售户限量'),
    sa.Column('C2', sa.Integer(), nullable=True, comment='C2零售户限量'),
    sa.Column('C3', sa.Integer(), nullable=True, comment='C3零售户限量'),
    sa.Column('C4', sa.Integer(), nullable=True, comment='C4零售户限量'),
    sa.Column('D1', sa.Integer(), nullable=True, comment='D1零售户限量'),
    sa.Column('D2', sa.Integer(), nullable=True, comment='D2零售户限量'),
    sa.Column('D3', sa.Integer(), nullable=True, comment='D3零售户限量'),
    sa.Column('D4', sa.Integer(), nullable=True, comment='D4零售户限量'),
    sa.Column('E1', sa.Integer(), nullable=True, comment='E1零售户限量'),
    sa.Column('E2', sa.Integer(), nullable=True, comment='E2零售户限量'),
    sa.Column('E3', sa.Integer(), nullable=True, comment='E3零售户限量'),
    sa.Column('E4', sa.Integer(), nullable=True, comment='E4零售户限量'),
    sa.Column('F1', sa.Integer(), nullable=True, comment='F1零售户限量'),
    sa.Column('F2', sa.Integer(), nullable=True, comment='F2零售户限量'),
    sa.Column('F3', sa.Integer(), nullable=True, comment='F3零售户限量'),
    sa.Column('F4', sa.Integer(), nullable=True, comment='F4零售户限量'),
    sa.Column('G1', sa.Integer(), nullable=True, comment='G1零售户限量'),
    sa.Column('G2', sa.Integer(), nullable=True, comment='G2零售户限量'),
    sa.Column('G3', sa.Integer(), nullable=True, comment='G3零售户限量'),
    sa.Column('G4', sa.Integer(), nullable=True, comment='G4零售户限量'),
    sa.Column('H1', sa.Integer(), nullable=True, comment='H1零售户限量'),
    sa.Column('H2', sa.Integer(), nullable=True, comment='H2零售户限量'),
    sa.Column('L2', sa.Integer(), nullable=True, comment='L2零售户限量'),
    sa.Column('L3', sa.Integer(), nullable=True, comment='L3零售户限量'),
    sa.Column('L4', sa.Integer(), nullable=True, comment='L4零售户限量'),
    sa.Column('L5', sa.Integer(), nullable=True, comment='L5零售户限量'),
    sa.Column('T1', sa.Integer(), nullable=True, comment='T1零售户限量'),
    sa.Column('T2', sa.Integer(), nullable=True, comment='T2零售户限量'),
    sa.Column('limit_startdate', sa.Date(), nullable=True, comment='限量起始日期'),
    sa.Column('limit_enddate', sa.Date(), nullable=True, comment='限量截止日期'),
    sa.ForeignKeyConstraint(['subbrand_id'], ['singlebrand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_limit_is_delete'), 'limit', ['is_delete'], unique=False)
    op.create_table('mon_pur_growthrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('singlebrand_id', sa.Integer(), nullable=True, comment='品规名称id'),
    sa.Column('parameter1', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='参数一'),
    sa.Column('parameter2', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='参数二'),
    sa.Column('parameter3', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='参数三'),
    sa.Column('parameter4', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='参数四'),
    sa.Column('score1', sa.Integer(), nullable=True, comment='分数一'),
    sa.Column('score2', sa.Integer(), nullable=True, comment='分数二'),
    sa.Column('score3', sa.Integer(), nullable=True, comment='分数三'),
    sa.Column('score4', sa.Integer(), nullable=True, comment='分数四'),
    sa.Column('score5', sa.Integer(), nullable=True, comment='分数五'),
    sa.Column('describe', sa.String(length=128), nullable=True, comment='预警参数描述'),
    sa.Column('modifydate', sa.Date(), nullable=True, comment='修改日期'),
    sa.ForeignKeyConstraint(['singlebrand_id'], ['singlebrand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mon_pur_growthrate_is_delete'), 'mon_pur_growthrate', ['is_delete'], unique=False)
    op.create_table('role_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment=' 角色id'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='权限id'),
    sa.ForeignKeyConstraint(['author_id'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_author_is_delete'), 'role_author', ['is_delete'], unique=False)
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('store_name', sa.String(length=128), nullable=False, comment='零售户名称'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='所属稽查所id'),
    sa.Column('person_id', sa.Integer(), nullable=False, comment='零售户法人信息id'),
    sa.Column('picture', sa.String(length=200), nullable=True, comment='店铺俯视图'),
    sa.Column('business_number', sa.String(length=200), nullable=True, comment='烟草经营许可证号'),
    sa.Column('is_bigillegal', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否是违法大户'),
    sa.Column('business_start', sa.Date(), nullable=True, comment='许可证有效期限起'),
    sa.Column('business_termi', sa.Date(), nullable=True, comment='许可证有效期限止'),
    sa.Column('longitude', sa.String(length=20), nullable=False, comment='地址经度'),
    sa.Column('latitude', sa.String(length=20), nullable=False, comment='地址维度'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='经营地址'),
    sa.Column('state', sa.Enum('NARMAL', 'CLOSE', 'REST', name='stateenum'), nullable=True, comment='经营状态'),
    sa.Column('store_category', sa.String(length=20), nullable=True, comment='零售户合理定量类别'),
    sa.Column('is_chain', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否连锁，True连锁 False不连锁'),
    sa.Column('is_suspension', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否暂停货源，True是 False不是'),
    sa.Column('business_format', sa.Enum('TOP', 'MIDDLE', 'LOW', name='businessformatenum'), nullable=True, comment='经营业态'),
    sa.Column('administrative', sa.Enum('BENJI', 'LANXI', 'PUJIANG', 'YIWU', 'DONGYANG', 'PANAN', 'YONGKANG', 'WUYI', name='adminienum'), nullable=True, comment='行政区划'),
    sa.Column('market_type', sa.Enum('COUNTRYSIDE', 'TOWNSHIP', 'COUNTRYTOWN', 'URBAN', name='markettypeenum'), nullable=True, comment='市场类型'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='主呼电话'),
    sa.Column('settlement_account', sa.String(length=200), nullable=True, comment='电子结算账号'),
    sa.Column('circle', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否敏感商圈，True敏感(商工住) False不敏感(文办混)'),
    sa.Column('is_downgrade', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否有降级降档情况，True有 False没有'),
    sa.Column('car_1', sa.String(length=200), nullable=True, comment='车辆牌照1'),
    sa.Column('car_2', sa.String(length=200), nullable=True, comment='车辆牌照2'),
    sa.Column('car_3', sa.String(length=200), nullable=True, comment='车辆牌照3'),
    sa.Column('car_photo1', sa.String(length=200), nullable=True, comment='车辆牌照图1'),
    sa.Column('car_photo2', sa.String(length=200), nullable=True, comment='车辆牌照图2'),
    sa.Column('car_photo3', sa.String(length=200), nullable=True, comment='车辆牌照图3'),
    sa.Column('operators1', sa.String(length=200), nullable=True, comment='日常经营人1'),
    sa.Column('license_ship1', sa.Enum('EMPLOY', 'RELATION', 'SELF', 'OTHER', name='licenseshipenum'), nullable=True, comment='与持证人关系1'),
    sa.Column('operators2', sa.String(length=200), nullable=True, comment='日常经营人2'),
    sa.Column('license_ship2', sa.Enum('EMPLOY', 'RELATION', 'SELF', 'OTHER', name='licenseshipenum'), nullable=True, comment='与持证人关系2'),
    sa.Column('operators3', sa.String(length=200), nullable=True, comment='日常经营人3'),
    sa.Column('license_ship3', sa.Enum('EMPLOY', 'RELATION', 'SELF', 'OTHER', name='licenseshipenum'), nullable=True, comment='与持证人关系3'),
    sa.Column('special_category', sa.Enum('VIOLENCE', 'PSYCHOSIS', 'IMPORTUNE', 'COMPLAINT', 'COMPLEX', name='specialgroupenum'), nullable=True, comment='特殊群体类别'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['personinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_circle'), 'store', ['circle'], unique=False)
    op.create_index(op.f('ix_store_is_delete'), 'store', ['is_delete'], unique=False)
    op.create_index(op.f('ix_store_is_downgrade'), 'store', ['is_downgrade'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('account', sa.String(length=64), nullable=False, comment='账户'),
    sa.Column('user_name', sa.String(length=50), nullable=True, comment='真实姓名'),
    sa.Column('password', sa.String(length=500), nullable=False, comment='密码'),
    sa.Column('station_id', sa.Integer(), nullable=True, comment=' 局id'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='稽查所id'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment=' 角色id'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_is_delete'), 'user', ['is_delete'], unique=False)
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='零售户id'),
    sa.Column('inspector_id', sa.Integer(), nullable=False, comment='稽查人员id'),
    sa.Column('audit_date', sa.Date(), nullable=False, comment='稽查时间'),
    sa.Column('audit_pic1', sa.String(length=128), nullable=True, comment='稽查情况照片1'),
    sa.Column('audit_pic2', sa.String(length=128), nullable=True, comment='稽查情况照片2'),
    sa.Column('audit_pic3', sa.String(length=128), nullable=True, comment='稽查情况照片3'),
    sa.Column('audit_pic4', sa.String(length=128), nullable=True, comment='稽查情况照片4'),
    sa.Column('audit_pic5', sa.String(length=128), nullable=True, comment='稽查情况照片5'),
    sa.Column('audit_pic6', sa.String(length=128), nullable=True, comment='稽查情况照片6'),
    sa.Column('audit_result', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='稽查结果反馈'),
    sa.Column('audit_note', sa.String(length=255), nullable=True, comment='稽查情况备注'),
    sa.Column('is_opensale', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否公开摆卖'),
    sa.Column('measures', sa.Enum('ORAL', 'ORDER', 'COMMON', 'CORRECTION', name='measuresenum'), nullable=True, comment='采取措施'),
    sa.Column('is_holdcertificate', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否持证经营'),
    sa.Column('is_opencertificate', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否亮证经营'),
    sa.Column('is_saleticket', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否销售烟票'),
    sa.Column('is_saleskyprice', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否存在天价烟销售'),
    sa.Column('is_potentially_illegal', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否有潜在违法行为'),
    sa.Column('score', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='评分'),
    sa.ForeignKeyConstraint(['inspector_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_audit_result'), 'audit', ['audit_result'], unique=False)
    op.create_index(op.f('ix_audit_is_delete'), 'audit', ['is_delete'], unique=False)
    op.create_index(op.f('ix_audit_is_holdcertificate'), 'audit', ['is_holdcertificate'], unique=False)
    op.create_index(op.f('ix_audit_is_opencertificate'), 'audit', ['is_opencertificate'], unique=False)
    op.create_index(op.f('ix_audit_is_opensale'), 'audit', ['is_opensale'], unique=False)
    op.create_index(op.f('ix_audit_is_potentially_illegal'), 'audit', ['is_potentially_illegal'], unique=False)
    op.create_index(op.f('ix_audit_is_saleskyprice'), 'audit', ['is_saleskyprice'], unique=False)
    op.create_index(op.f('ix_audit_is_saleticket'), 'audit', ['is_saleticket'], unique=False)
    op.create_table('bpdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='零售户id'),
    sa.Column('whole_illegaltimes', sa.Integer(), nullable=True, comment='历史总违法次数'),
    sa.Column('twoyear_illegaltimes', sa.Integer(), nullable=True, comment='近两年内违法次数'),
    sa.Column('is_halfyear_illegal', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='近半年内是否有违法记录,True 有 False 没有'),
    sa.Column('is_criminal', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否有过刑事处罚 True 是  False 否'),
    sa.Column('format', sa.Integer(), nullable=True, comment='经营业态'),
    sa.Column('is_sensitivecircle', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否处于敏感商圈   True 是  False 否'),
    sa.Column('is_downgrade', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否有过降级降档  True 是  False 否'),
    sa.Column('is_bigillegal', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否违法大户  True 是  False 否'),
    sa.Column('is_sensitive_canton', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='法人是否是敏感籍贯  True 是  False  否'),
    sa.Column('purchase_change', sa.FLOAT(precision=4), nullable=True, comment='进货量增长率a'),
    sa.Column('required_differ', sa.FLOAT(precision=2), nullable=True, comment='要货量-进货量差值a'),
    sa.Column('purchase_price', sa.FLOAT(precision=4), nullable=True, comment='平均进货单价增长率a'),
    sa.Column('sensitive_month', sa.Integer(), nullable=True, comment='敏感时间等级'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('bp_result', sa.FLOAT(precision=4), nullable=True, comment='预测结果'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('caseId', sa.String(length=128), nullable=False, comment='案件编号'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment=' 零售户id'),
    sa.Column('case_date', sa.Date(), nullable=True, comment='案发时间'),
    sa.Column('case_value', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='案值'),
    sa.Column('count', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='卷烟数量（条数）'),
    sa.Column('case_nature', sa.String(length=128), nullable=True, comment='案件性质'),
    sa.Column('is_criminal', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='有无刑事处罚，True有 False没有'),
    sa.Column('smoke_property01', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否为非流烟，True是 False否'),
    sa.Column('smoke_property02', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否为假冒烟，True是 False否'),
    sa.Column('smoke_property03', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否为走私烟，True是 False否'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_is_criminal'), 'case', ['is_criminal'], unique=False)
    op.create_index(op.f('ix_case_is_delete'), 'case', ['is_delete'], unique=False)
    op.create_index(op.f('ix_case_smoke_property01'), 'case', ['smoke_property01'], unique=False)
    op.create_index(op.f('ix_case_smoke_property02'), 'case', ['smoke_property02'], unique=False)
    op.create_index(op.f('ix_case_smoke_property03'), 'case', ['smoke_property03'], unique=False)
    op.create_table('codesegment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='零售户id'),
    sa.Column('out_date', sa.Date(), nullable=True, comment='外流时间'),
    sa.Column('cigar_name', sa.String(length=128), nullable=True, comment='外流品规名称'),
    sa.Column('out_count', sa.DECIMAL(precision=8, scale=1), nullable=True, comment='外流条数（条）'),
    sa.Column('spray_code', sa.String(length=16), nullable=True, comment='喷码后16位'),
    sa.Column('out_place', sa.String(length=128), nullable=True, comment='外流地'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codesegment_is_delete'), 'codesegment', ['is_delete'], unique=False)
    op.create_table('forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='零售户id'),
    sa.Column('forecast_date', sa.Date(), nullable=True, comment='预测时间'),
    sa.Column('mode', sa.Enum('SVM', 'BP', 'RULE', name='modelenum'), nullable=True, comment='预测模型'),
    sa.Column('result', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='预测违法可能性'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_is_delete'), 'forecast', ['is_delete'], unique=False)
    op.create_table('forecast_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('forecast_store_id', sa.Integer(), nullable=False, comment='预测违法零售户id'),
    sa.Column('forecast_mode', sa.String(length=50), nullable=True, comment='预测模型（综合/规则）'),
    sa.Column('forecast_result', sa.Enum('TOP', 'MIDDLE', 'LOW', name='foreenum'), nullable=True, comment='预测结果等级（高中低）'),
    sa.ForeignKeyConstraint(['forecast_store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_store_is_delete'), 'forecast_store', ['is_delete'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment=' 零售户id'),
    sa.Column('purchase_date', sa.Date(), nullable=True, comment='进货时间'),
    sa.Column('purchase_week', sa.Integer(), nullable=True, comment='周进货总量（条）'),
    sa.Column('settlement_account', sa.String(length=128), nullable=True, comment='进货结算账号'),
    sa.Column('required_count', sa.Integer(), nullable=True, comment='要货总量'),
    sa.Column('average_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='平均进货单价（元）'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_is_delete'), 'purchase', ['is_delete'], unique=False)
    op.create_table('ruledata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('store_id', sa.Integer(), nullable=True, comment='零售户id'),
    sa.Column('person_nativeplace', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='主要经营人籍贯，True是 False否'),
    sa.Column('person01_nativeplace', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='其他经营人1籍贯，True是 False否'),
    sa.Column('person02_nativeplace', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='其他经营人2籍贯，True是 False否'),
    sa.Column('is_bigillegal', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否为违法大户，True是 False否'),
    sa.Column('is_downgrade', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否有降级将档情况，True是 False否'),
    sa.Column('month', sa.Integer(), nullable=True, comment='当前月'),
    sa.Column('canton_id', sa.Integer(), nullable=True, comment='行政区id'),
    sa.Column('is_criminal', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='有无刑事处罚，True是 False否'),
    sa.Column('is_illegal', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='近半年内是否有违法记录，True是 False否'),
    sa.Column('cigar_property_jia', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否假冒烟，True是 False否'),
    sa.Column('cigar_property_fei', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否非流烟，True是 False否'),
    sa.Column('cigar_property_zou', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否走私烟，True是 False否'),
    sa.Column('logistics', sa.Integer(), nullable=True, comment='物流'),
    sa.Column('car', sa.Integer(), nullable=True, comment='车辆'),
    sa.Column('unlicensed_transport_times', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='无证运输烟草专卖品次数'),
    sa.Column('unlicensed_transport_num', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='无证运输烟草专卖品条数'),
    sa.Column('unlicensed_transport_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='无证运输烟草专卖品金额'),
    sa.Column('purchase_illegcigar_times', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='未在当地进货次数'),
    sa.Column('purchase_illegcigar_num', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='未在当地进货条数'),
    sa.Column('purchase_illegcigar_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='未在当地进货金额'),
    sa.Column('sell_illegcigar_times', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='销售非法生产的烟草专卖次数'),
    sa.Column('sell_illegcigar_num', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='销售非法生产的烟草专卖条数'),
    sa.Column('sell_illegcigar_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='销售非法生产的烟草专卖金额'),
    sa.Column('over_postcigar_times', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='无烟草专卖准运证运输烟草专卖品—邮寄、异地携带烟叶、烟草制品超过有关规定次数'),
    sa.Column('over_postcigar_num', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='无烟草专卖准运证运输烟草专卖品—邮寄、异地携带烟叶、烟草制品超过有关规定条数'),
    sa.Column('over_postcigar_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='无烟草专卖准运证运输烟草专卖品—邮寄、异地携带烟叶、烟草制品超过有关规定金额'),
    sa.Column('sell_abroadcigar_times', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='销售无标识外国卷烟 或 销售出口倒流国产卷烟 或 销售没收的非法进口卷烟次数'),
    sa.Column('sell_abroadcigar_num', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='销售无标识外国卷烟 或 销售出口倒流国产卷烟 或 销售没收的非法进口卷烟条数'),
    sa.Column('sell_abroadcigar_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='销售无标识外国卷烟 或 销售出口倒流国产卷烟 或 销售没收的非法进口卷烟金额'),
    sa.Column('helpothers_transport_times', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='无烟草专卖准运证运输烟草专卖品—为无烟草专卖品准运证者承运烟草专卖品次数'),
    sa.Column('helpothers_transport_num', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='无烟草专卖准运证运输烟草专卖品—为无烟草专卖品准运证者承运烟草专卖品条数'),
    sa.Column('helpothers_transport_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='无烟草专卖准运证运输烟草专卖品—为无烟草专卖品准运证者承运烟草专卖品金额'),
    sa.Column('twoyear_illegaltimes', sa.Integer(), nullable=True, comment='近两年历史违法次数'),
    sa.Column('in_province_times', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='近一年码段外流情况（省内外流）次数'),
    sa.Column('in_province_num', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='近一年码段外流情况（省内外流）条数'),
    sa.Column('in_province_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='近一年码段外流情况（省内外流）金额'),
    sa.Column('out_of_province_times', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='近一年码段外流情况（外流省外）次数'),
    sa.Column('out_of_province_num', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='近一年码段外流情况（外流省外）条数'),
    sa.Column('out_of_province_price', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='近一年码段外流情况（外流省外）金额'),
    sa.Column('score', sa.Integer(), nullable=True, comment='规则预测得分'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ruledata_cigar_property_fei'), 'ruledata', ['cigar_property_fei'], unique=False)
    op.create_index(op.f('ix_ruledata_cigar_property_jia'), 'ruledata', ['cigar_property_jia'], unique=False)
    op.create_index(op.f('ix_ruledata_cigar_property_zou'), 'ruledata', ['cigar_property_zou'], unique=False)
    op.create_index(op.f('ix_ruledata_is_bigillegal'), 'ruledata', ['is_bigillegal'], unique=False)
    op.create_index(op.f('ix_ruledata_is_criminal'), 'ruledata', ['is_criminal'], unique=False)
    op.create_index(op.f('ix_ruledata_is_delete'), 'ruledata', ['is_delete'], unique=False)
    op.create_index(op.f('ix_ruledata_is_downgrade'), 'ruledata', ['is_downgrade'], unique=False)
    op.create_index(op.f('ix_ruledata_is_illegal'), 'ruledata', ['is_illegal'], unique=False)
    op.create_index(op.f('ix_ruledata_person01_nativeplace'), 'ruledata', ['person01_nativeplace'], unique=False)
    op.create_index(op.f('ix_ruledata_person02_nativeplace'), 'ruledata', ['person02_nativeplace'], unique=False)
    op.create_index(op.f('ix_ruledata_person_nativeplace'), 'ruledata', ['person_nativeplace'], unique=False)
    op.create_table('storerelationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('social_relationshipid', sa.Integer(), nullable=True, comment='所属稽查所id'),
    sa.Column('store1_id', sa.Integer(), nullable=True, comment='所属稽查所id'),
    sa.Column('store2_id', sa.Integer(), nullable=True, comment='所属稽查所id'),
    sa.ForeignKeyConstraint(['social_relationshipid'], ['storerelationship.id'], ),
    sa.ForeignKeyConstraint(['store1_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['store2_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storerelationship_is_delete'), 'storerelationship', ['is_delete'], unique=False)
    op.create_table('svmdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='零售户id'),
    sa.Column('whole_illegaltimes', sa.Integer(), nullable=True, comment='历史总违法次数'),
    sa.Column('twoyear_illegaltimes', sa.Integer(), nullable=True, comment='近两年内违法次数'),
    sa.Column('is_halfyear_illegal', sa.Integer(), nullable=True, comment='近半年内是否有违法记录,True 有 False 没有'),
    sa.Column('maximum_cigar_num', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='最大涉烟条数'),
    sa.Column('outofprovince_times', sa.Integer(), nullable=True, comment='码段外流次数'),
    sa.Column('maximum_outofprovince_num', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='最大外流条数'),
    sa.Column('is_criminal', sa.Integer(), nullable=True, comment='是否有过刑事处罚 True 是  False 否'),
    sa.Column('format', sa.Integer(), nullable=True, comment='经营业态'),
    sa.Column('is_sensitivecircle', sa.Integer(), nullable=True, comment='是否处于敏感商圈   True 是  False 否'),
    sa.Column('is_downgrade', sa.Integer(), nullable=True, comment='是否有过降级降档  True 是  False 否'),
    sa.Column('is_bigillegal', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否违法大户  True 是  False 否'),
    sa.Column('is_sensitive_canton', sa.Integer(), nullable=True, comment='法人是否是敏感籍贯  True 是  False  否'),
    sa.Column('is_sensitive_nativeplace', sa.Integer(), nullable=True, comment='是否处于敏感行政区  True 是  False  否'),
    sa.Column('purchase_change', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='进货量增长率'),
    sa.Column('required_differ', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='要货量-进货量差值'),
    sa.Column('purchase_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='平均进货单价增长率'),
    sa.Column('sensitive_month', sa.Integer(), nullable=True, comment='敏感时间等级'),
    sa.Column('result', sa.Integer(), nullable=True, comment='预测结果'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_svmdata_is_delete'), 'svmdata', ['is_delete'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment=' 角色id'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_is_delete'), 'user_role', ['is_delete'], unique=False)
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('purchase_id', sa.Integer(), nullable=False, comment='进货记录id'),
    sa.Column('cigar_name', sa.String(length=128), nullable=True, comment='品规名称'),
    sa.Column('cigar_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='进货单价（元）'),
    sa.Column('cigar_num', sa.Integer(), nullable=True, comment='进货量（条）'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_is_delete'), 'brand', ['is_delete'], unique=False)
    op.create_table('casecigar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('case_id', sa.Integer(), nullable=False, comment=' 违法案件id'),
    sa.Column('cigar_property', sa.Enum('COUNTERFEIT', 'SMUGGLE', 'DOMESTIC', name='cigarattributeenum'), nullable=True, comment='涉烟属性'),
    sa.Column('singlebrand_id', sa.Integer(), nullable=False, comment='品规id'),
    sa.Column('count', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='卷烟数量（条数）'),
    sa.Column('origin_area', sa.String(length=128), nullable=False, comment='来源地'),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['singlebrand_id'], ['singlebrand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casecigar_is_delete'), 'casecigar', ['is_delete'], unique=False)
    op.create_table('hidepicture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='零售户id'),
    sa.Column('audit_id', sa.Integer(), nullable=False, comment='稽查记录id'),
    sa.Column('picture', sa.String(length=200), nullable=True, comment='藏匿图'),
    sa.Column('graffiti', sa.String(length=200), nullable=True, comment='涂鸦'),
    sa.Column('note', sa.String(length=128), nullable=True, comment='藏匿图文字备注'),
    sa.ForeignKeyConstraint(['audit_id'], ['audit.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hidepicture_is_delete'), 'hidepicture', ['is_delete'], unique=False)
    op.create_table('codetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('False'), nullable=True, comment='是否删除，True已删 False未删'),
    sa.Column('singlebrand_id', sa.Integer(), nullable=False, comment='品规id'),
    sa.Column('case_cigarid', sa.Integer(), nullable=False, comment='违法涉烟详情id'),
    sa.Column('cigar_codefront', sa.String(length=128), nullable=False, comment='前16位喷码'),
    sa.Column('cigar_codebehind', sa.String(length=128), nullable=False, comment='后16位喷码'),
    sa.ForeignKeyConstraint(['case_cigarid'], ['casecigar.id'], ),
    sa.ForeignKeyConstraint(['singlebrand_id'], ['singlebrand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codetable_is_delete'), 'codetable', ['is_delete'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codetable_is_delete'), table_name='codetable')
    op.drop_table('codetable')
    op.drop_index(op.f('ix_hidepicture_is_delete'), table_name='hidepicture')
    op.drop_table('hidepicture')
    op.drop_index(op.f('ix_casecigar_is_delete'), table_name='casecigar')
    op.drop_table('casecigar')
    op.drop_index(op.f('ix_brand_is_delete'), table_name='brand')
    op.drop_table('brand')
    op.drop_index(op.f('ix_user_role_is_delete'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_svmdata_is_delete'), table_name='svmdata')
    op.drop_table('svmdata')
    op.drop_index(op.f('ix_storerelationship_is_delete'), table_name='storerelationship')
    op.drop_table('storerelationship')
    op.drop_index(op.f('ix_ruledata_person_nativeplace'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_person02_nativeplace'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_person01_nativeplace'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_is_illegal'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_is_downgrade'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_is_delete'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_is_criminal'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_is_bigillegal'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_cigar_property_zou'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_cigar_property_jia'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_cigar_property_fei'), table_name='ruledata')
    op.drop_table('ruledata')
    op.drop_index(op.f('ix_purchase_is_delete'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_forecast_store_is_delete'), table_name='forecast_store')
    op.drop_table('forecast_store')
    op.drop_index(op.f('ix_forecast_is_delete'), table_name='forecast')
    op.drop_table('forecast')
    op.drop_index(op.f('ix_codesegment_is_delete'), table_name='codesegment')
    op.drop_table('codesegment')
    op.drop_index(op.f('ix_case_smoke_property03'), table_name='case')
    op.drop_index(op.f('ix_case_smoke_property02'), table_name='case')
    op.drop_index(op.f('ix_case_smoke_property01'), table_name='case')
    op.drop_index(op.f('ix_case_is_delete'), table_name='case')
    op.drop_index(op.f('ix_case_is_criminal'), table_name='case')
    op.drop_table('case')
    op.drop_table('bpdata')
    op.drop_index(op.f('ix_audit_is_saleticket'), table_name='audit')
    op.drop_index(op.f('ix_audit_is_saleskyprice'), table_name='audit')
    op.drop_index(op.f('ix_audit_is_potentially_illegal'), table_name='audit')
    op.drop_index(op.f('ix_audit_is_opensale'), table_name='audit')
    op.drop_index(op.f('ix_audit_is_opencertificate'), table_name='audit')
    op.drop_index(op.f('ix_audit_is_holdcertificate'), table_name='audit')
    op.drop_index(op.f('ix_audit_is_delete'), table_name='audit')
    op.drop_index(op.f('ix_audit_audit_result'), table_name='audit')
    op.drop_table('audit')
    op.drop_index(op.f('ix_user_is_delete'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_store_is_downgrade'), table_name='store')
    op.drop_index(op.f('ix_store_is_delete'), table_name='store')
    op.drop_index(op.f('ix_store_circle'), table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('ix_role_author_is_delete'), table_name='role_author')
    op.drop_table('role_author')
    op.drop_index(op.f('ix_mon_pur_growthrate_is_delete'), table_name='mon_pur_growthrate')
    op.drop_table('mon_pur_growthrate')
    op.drop_index(op.f('ix_limit_is_delete'), table_name='limit')
    op.drop_table('limit')
    op.drop_index(op.f('ix_department_is_delete'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_warning_is_delete'), table_name='warning')
    op.drop_table('warning')
    op.drop_index(op.f('ix_station_is_delete'), table_name='station')
    op.drop_table('station')
    op.drop_index(op.f('ix_socialrelationship_is_delete'), table_name='socialrelationship')
    op.drop_table('socialrelationship')
    op.drop_index(op.f('ix_singlebrand_is_sale'), table_name='singlebrand')
    op.drop_index(op.f('ix_singlebrand_is_delete'), table_name='singlebrand')
    op.drop_table('singlebrand')
    op.drop_index(op.f('ix_role_is_delete'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_predictrule_parameter4'), table_name='predictrule')
    op.drop_index(op.f('ix_predictrule_is_delete'), table_name='predictrule')
    op.drop_table('predictrule')
    op.drop_index(op.f('ix_personinfo_is_delete'), table_name='personinfo')
    op.drop_table('personinfo')
    op.drop_index(op.f('ix_monthtable_is_delete'), table_name='monthtable')
    op.drop_table('monthtable')
    op.drop_index(op.f('ix_excelinandout_is_delete'), table_name='excelinandout')
    op.drop_table('excelinandout')
    op.drop_index(op.f('ix_canton_is_delete'), table_name='canton')
    op.drop_index(op.f('ix_canton_is_cantonsensitivity'), table_name='canton')
    op.drop_table('canton')
    op.drop_index(op.f('ix_businessformat_is_delete'), table_name='businessformat')
    op.drop_table('businessformat')
    op.drop_index(op.f('ix_authorities_is_delete'), table_name='authorities')
    op.drop_table('authorities')
    # ### end Alembic commands ###
