"""empty message

Revision ID: a6e8ed230a04
Revises: fa71962847ca
Create Date: 2020-06-03 12:16:23.521451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e8ed230a04'
down_revision = 'fa71962847ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_inspector_id'), 'audit', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_audit_store_id'), 'audit', ['store_id'], unique=False)
    op.create_index(op.f('ix_brand_purchase_id'), 'brand', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_case_caseId'), 'case', ['caseId'], unique=False)
    op.create_index(op.f('ix_case_store_id'), 'case', ['store_id'], unique=False)
    op.create_index(op.f('ix_casecigar_business_number'), 'casecigar', ['business_number'], unique=False)
    op.create_index(op.f('ix_casecigar_case_date'), 'casecigar', ['case_date'], unique=False)
    op.create_index(op.f('ix_casecigar_case_id'), 'casecigar', ['case_id'], unique=False)
    op.create_index(op.f('ix_casecigar_cigar_codebehind'), 'casecigar', ['cigar_codebehind'], unique=False)
    op.create_index(op.f('ix_casecigar_cigar_codefront'), 'casecigar', ['cigar_codefront'], unique=False)
    op.create_index(op.f('ix_casecigar_store_name'), 'casecigar', ['store_name'], unique=False)
    op.create_index(op.f('ix_hidepicture_audit_id'), 'hidepicture', ['audit_id'], unique=False)
    op.create_index(op.f('ix_hidepicture_store_id'), 'hidepicture', ['store_id'], unique=False)
    op.create_index(op.f('ix_personinfo_name'), 'personinfo', ['name'], unique=False)
    op.create_index(op.f('ix_purchase_store_id'), 'purchase', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_department_id'), 'store', ['department_id'], unique=False)
    op.create_index(op.f('ix_store_person_id'), 'store', ['person_id'], unique=False)
    op.create_index(op.f('ix_store_store_name'), 'store', ['store_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_store_name'), table_name='store')
    op.drop_index(op.f('ix_store_person_id'), table_name='store')
    op.drop_index(op.f('ix_store_department_id'), table_name='store')
    op.drop_index(op.f('ix_purchase_store_id'), table_name='purchase')
    op.drop_index(op.f('ix_personinfo_name'), table_name='personinfo')
    op.drop_index(op.f('ix_hidepicture_store_id'), table_name='hidepicture')
    op.drop_index(op.f('ix_hidepicture_audit_id'), table_name='hidepicture')
    op.drop_index(op.f('ix_casecigar_store_name'), table_name='casecigar')
    op.drop_index(op.f('ix_casecigar_cigar_codefront'), table_name='casecigar')
    op.drop_index(op.f('ix_casecigar_cigar_codebehind'), table_name='casecigar')
    op.drop_index(op.f('ix_casecigar_case_id'), table_name='casecigar')
    op.drop_index(op.f('ix_casecigar_case_date'), table_name='casecigar')
    op.drop_index(op.f('ix_casecigar_business_number'), table_name='casecigar')
    op.drop_index(op.f('ix_case_store_id'), table_name='case')
    op.drop_index(op.f('ix_case_caseId'), table_name='case')
    op.drop_index(op.f('ix_brand_purchase_id'), table_name='brand')
    op.drop_index(op.f('ix_audit_store_id'), table_name='audit')
    op.drop_index(op.f('ix_audit_inspector_id'), table_name='audit')
    # ### end Alembic commands ###
