"""empty message

Revision ID: d89ad2f83575
Revises: 9d148d9e510b
Create Date: 2020-06-03 17:48:23.605062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89ad2f83575'
down_revision = '9d148d9e510b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_id'), 'audit', ['id'], unique=False)
    op.create_index(op.f('ix_authorities_id'), 'authorities', ['id'], unique=False)
    op.create_index(op.f('ix_bpdata_store_id'), 'bpdata', ['store_id'], unique=False)
    op.create_index(op.f('ix_brand_id'), 'brand', ['id'], unique=False)
    op.create_index(op.f('ix_businessformat_id'), 'businessformat', ['id'], unique=False)
    op.create_index(op.f('ix_canton_id'), 'canton', ['id'], unique=False)
    op.create_index(op.f('ix_case_id'), 'case', ['id'], unique=False)
    op.create_index(op.f('ix_casecigar_id'), 'casecigar', ['id'], unique=False)
    op.create_index(op.f('ix_circle_id'), 'circle', ['id'], unique=False)
    op.create_index(op.f('ix_codesegment_id'), 'codesegment', ['id'], unique=False)
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_index(op.f('ix_excelinandout_id'), 'excelinandout', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_id'), 'forecast', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_store_id'), 'forecast', ['store_id'], unique=False)
    op.create_index(op.f('ix_forecast_store_forecast_store_id'), 'forecast_store', ['forecast_store_id'], unique=False)
    op.create_index(op.f('ix_forecast_store_id'), 'forecast_store', ['id'], unique=False)
    op.create_index(op.f('ix_hidepicture_id'), 'hidepicture', ['id'], unique=False)
    op.create_index(op.f('ix_limit_id'), 'limit', ['id'], unique=False)
    op.create_index(op.f('ix_mon_pur_growthrate_id'), 'mon_pur_growthrate', ['id'], unique=False)
    op.create_index(op.f('ix_monthtable_id'), 'monthtable', ['id'], unique=False)
    op.create_index(op.f('ix_personinfo_id'), 'personinfo', ['id'], unique=False)
    op.create_index(op.f('ix_predictrule_id'), 'predictrule', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_id'), 'purchase', ['id'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_author_id'), 'role_author', ['id'], unique=False)
    op.create_index(op.f('ix_ruledata_id'), 'ruledata', ['id'], unique=False)
    op.create_index(op.f('ix_ruledata_store_id'), 'ruledata', ['store_id'], unique=False)
    op.create_index(op.f('ix_singlebrand_id'), 'singlebrand', ['id'], unique=False)
    op.create_index(op.f('ix_socialrelationship_id'), 'socialrelationship', ['id'], unique=False)
    op.create_index(op.f('ix_station_id'), 'station', ['id'], unique=False)
    op.create_index(op.f('ix_store_id'), 'store', ['id'], unique=False)
    op.create_index(op.f('ix_storerelationship_id'), 'storerelationship', ['id'], unique=False)
    op.create_index(op.f('ix_svmdata_id'), 'svmdata', ['id'], unique=False)
    op.create_index(op.f('ix_svmdata_store_id'), 'svmdata', ['store_id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    op.create_index(op.f('ix_warning_id'), 'warning', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warning_id'), table_name='warning')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_svmdata_store_id'), table_name='svmdata')
    op.drop_index(op.f('ix_svmdata_id'), table_name='svmdata')
    op.drop_index(op.f('ix_storerelationship_id'), table_name='storerelationship')
    op.drop_index(op.f('ix_store_id'), table_name='store')
    op.drop_index(op.f('ix_station_id'), table_name='station')
    op.drop_index(op.f('ix_socialrelationship_id'), table_name='socialrelationship')
    op.drop_index(op.f('ix_singlebrand_id'), table_name='singlebrand')
    op.drop_index(op.f('ix_ruledata_store_id'), table_name='ruledata')
    op.drop_index(op.f('ix_ruledata_id'), table_name='ruledata')
    op.drop_index(op.f('ix_role_author_id'), table_name='role_author')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_purchase_id'), table_name='purchase')
    op.drop_index(op.f('ix_predictrule_id'), table_name='predictrule')
    op.drop_index(op.f('ix_personinfo_id'), table_name='personinfo')
    op.drop_index(op.f('ix_monthtable_id'), table_name='monthtable')
    op.drop_index(op.f('ix_mon_pur_growthrate_id'), table_name='mon_pur_growthrate')
    op.drop_index(op.f('ix_limit_id'), table_name='limit')
    op.drop_index(op.f('ix_hidepicture_id'), table_name='hidepicture')
    op.drop_index(op.f('ix_forecast_store_id'), table_name='forecast_store')
    op.drop_index(op.f('ix_forecast_store_forecast_store_id'), table_name='forecast_store')
    op.drop_index(op.f('ix_forecast_store_id'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_id'), table_name='forecast')
    op.drop_index(op.f('ix_excelinandout_id'), table_name='excelinandout')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_index(op.f('ix_codesegment_id'), table_name='codesegment')
    op.drop_index(op.f('ix_circle_id'), table_name='circle')
    op.drop_index(op.f('ix_casecigar_id'), table_name='casecigar')
    op.drop_index(op.f('ix_case_id'), table_name='case')
    op.drop_index(op.f('ix_canton_id'), table_name='canton')
    op.drop_index(op.f('ix_businessformat_id'), table_name='businessformat')
    op.drop_index(op.f('ix_brand_id'), table_name='brand')
    op.drop_index(op.f('ix_bpdata_store_id'), table_name='bpdata')
    op.drop_index(op.f('ix_authorities_id'), table_name='authorities')
    op.drop_index(op.f('ix_audit_id'), table_name='audit')
    # ### end Alembic commands ###
