"""empty message

Revision ID: ee33c85db681
Revises: 2b70073c9ba2
Create Date: 2020-05-31 17:24:29.227888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee33c85db681'
down_revision = '2b70073c9ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bpdata', 'is_sensitivecircle',
                    type_=mysql.INTEGER(display_width=11),
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='是否处于敏感商圈',
                    existing_comment='是否处于敏感商圈   True 是  False 否',
                    existing_nullable=True,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('svmdata', 'is_sensitivecircle',
                    existing_type=mysql.INTEGER(display_width=11),
                    comment='是否处于敏感商圈',
                    existing_comment='是否处于敏感商圈   True 是  False 否',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('svmdata', 'is_sensitivecircle',
                    existing_type=mysql.INTEGER(display_width=11),
                    comment='是否处于敏感商圈   True 是  False 否',
                    existing_comment='是否处于敏感商圈',
                    existing_nullable=True)
    op.alter_column('bpdata', 'is_sensitivecircle',
                    type_=mysql.TINYINT(display_width=1),
                    existing_type=mysql.INTEGER(display_width=11),
                    comment='是否处于敏感商圈   True 是  False 否',
                    existing_comment='是否处于敏感商圈',
                    existing_nullable=True,
                    existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
