"""empty message

Revision ID: fa71962847ca
Revises: ee33c85db681
Create Date: 2020-06-01 23:21:58.877932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa71962847ca'
down_revision = 'ee33c85db681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_store', sa.Column('department_id', sa.Integer(), nullable=True, comment='零售户所属稽查所id'))
    op.add_column('forecast_store', sa.Column('forecast_date', sa.Date(), nullable=True, comment='预测时间'))
    op.add_column('forecast_store', sa.Column('station_id', sa.Integer(), nullable=True, comment='零售户所属专卖局id'))
    op.alter_column('forecast_store', 'forecast_mode',
               existing_type=mysql.VARCHAR(length=50),
               comment='预测模型',
               existing_comment='预测模型（综合/规则）',
               existing_nullable=True)
    op.alter_column('forecast_store', 'forecast_store_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='预测零售户id',
               existing_comment='预测违法零售户id',
               existing_nullable=False)
    op.create_foreign_key(None, 'forecast_store', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'forecast_store', 'station', ['station_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forecast_store', type_='foreignkey')
    op.drop_constraint(None, 'forecast_store', type_='foreignkey')
    op.alter_column('forecast_store', 'forecast_store_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='预测违法零售户id',
               existing_comment='预测零售户id',
               existing_nullable=False)
    op.alter_column('forecast_store', 'forecast_mode',
               existing_type=mysql.VARCHAR(length=50),
               comment='预测模型（综合/规则）',
               existing_comment='预测模型',
               existing_nullable=True)
    op.drop_column('forecast_store', 'station_id')
    op.drop_column('forecast_store', 'forecast_date')
    op.drop_column('forecast_store', 'department_id')
    # ### end Alembic commands ###
